redis:
  lock:
    mode: ${redis.lock.mode}
    addresses: ${redis.lock.addresses}
    password: ${redis.lock.password}
    database: ${redis.lock.database}
    enabled: ${redis.lock.enabled}
logging:
  level:
    root: info
    com.tiaohe: debug
    org.redisson: debug